2021-01-29 23:06:53,619 INFO    MainThread:3168 [wandb_setup.py:_flush():70] setting env: {'entity': 'dc925', 'project': 'graphmimic', 'sweep_id': 'dxwk7c7t', 'root_dir': '/home/dc925/project/graphmimic/code', 'run_id': 'ko53npka', 'sweep_param_path': '/home/dc925/project/graphmimic/code/wandb/sweep-dxwk7c7t/config-ko53npka.yaml'}
2021-01-29 23:06:53,619 INFO    MainThread:3168 [wandb_setup.py:_flush():70] multiprocessing start_methods=fork,spawn,forkserver
2021-01-29 23:06:53,619 INFO    MainThread:3168 [wandb_setup.py:_flush():70] setting login settings: {}
2021-01-29 23:06:53,619 INFO    MainThread:3168 [wandb_init.py:_log_setup():318] Logging user logs to /home/dc925/project/graphmimic/code/wandb/run-20210129_230653-ko53npka/logs/debug.log
2021-01-29 23:06:53,620 INFO    MainThread:3168 [wandb_init.py:_log_setup():319] Logging internal logs to /home/dc925/project/graphmimic/code/wandb/run-20210129_230653-ko53npka/logs/debug-internal.log
2021-01-29 23:06:53,639 INFO    MainThread:3168 [wandb_run.py:_config_callback():660] config_cb None None {'data_dir': '/home/dc925/project/data/graphmimic/sample/', 'learning_rate': 0.0001, 'max_seq_length': 128, 'model_name_or_path': 'xhlu/electra-medal', 'num_train_epochs': 4, 'output_dir': '/home/dc925/project/output/129/wandb', 'per_gpu_eval_batch_size': 32, 'per_gpu_train_batch_size': 16}
2021-01-29 23:06:55,780 INFO    MainThread:3168 [wandb_run.py:_console_start():1396] atexit reg
2021-01-29 23:06:55,781 INFO    MainThread:3168 [wandb_run.py:_redirect():1259] redirect: SettingsConsole.REDIRECT
2021-01-29 23:06:55,782 INFO    MainThread:3168 [wandb_run.py:_redirect():1264] Redirecting console.
2021-01-29 23:06:55,782 INFO    MainThread:3168 [redirect.py:install():213] install start
2021-01-29 23:06:55,782 INFO    MainThread:3168 [redirect.py:install():228] install stop
2021-01-29 23:06:55,783 INFO    MainThread:3168 [redirect.py:install():213] install start
2021-01-29 23:06:55,783 INFO    MainThread:3168 [redirect.py:install():228] install stop
2021-01-29 23:06:55,783 INFO    MainThread:3168 [wandb_run.py:_redirect():1310] Redirects installed.
2021-01-29 23:06:55,830 INFO    MainThread:3168 [wandb_run.py:_atexit_cleanup():1366] got exitcode: 1
2021-01-29 23:06:55,831 INFO    MainThread:3168 [wandb_run.py:_restore():1338] restore
2021-01-29 23:06:55,832 INFO    MainThread:3168 [redirect.py:uninstall():232] uninstall start
2021-01-29 23:06:55,832 INFO    MainThread:3168 [redirect.py:_stop():287] _stop: stdout
2021-01-29 23:06:55,832 INFO    MainThread:3168 [redirect.py:_stop():293] _stop closed: stdout
2021-01-29 23:06:55,832 INFO    stdout    :3168 [redirect.py:_pipe_relay():129] relay done saw last write: stdout
2021-01-29 23:06:55,833 INFO    stdout    :3168 [redirect.py:_pipe_relay():145] relay done done: stdout
2021-01-29 23:06:55,833 INFO    MainThread:3168 [redirect.py:_stop():299] _stop joined: stdout
2021-01-29 23:06:55,833 INFO    MainThread:3168 [redirect.py:_stop():301] _stop rd closed: stdout
2021-01-29 23:06:55,833 INFO    MainThread:3168 [redirect.py:uninstall():236] uninstall done
2021-01-29 23:06:55,833 INFO    MainThread:3168 [redirect.py:uninstall():232] uninstall start
2021-01-29 23:06:55,833 INFO    MainThread:3168 [redirect.py:_stop():287] _stop: stderr
2021-01-29 23:06:55,833 INFO    MainThread:3168 [redirect.py:_stop():293] _stop closed: stderr
2021-01-29 23:06:55,833 INFO    stderr    :3168 [redirect.py:_pipe_relay():129] relay done saw last write: stderr
2021-01-29 23:06:55,833 INFO    stderr    :3168 [redirect.py:_pipe_relay():145] relay done done: stderr
2021-01-29 23:06:55,834 INFO    MainThread:3168 [redirect.py:_stop():299] _stop joined: stderr
2021-01-29 23:06:55,834 INFO    MainThread:3168 [redirect.py:_stop():301] _stop rd closed: stderr
2021-01-29 23:06:55,834 INFO    MainThread:3168 [redirect.py:uninstall():236] uninstall done
2021-01-29 23:06:56,043 INFO    MainThread:3168 [wandb_run.py:_wait_for_finish():1489] got exit ret: file_counts {
  wandb_count: 1
}
pusher_stats {
  uploaded_bytes: 622
  total_bytes: 622
}

2021-01-29 23:06:58,048 INFO    MainThread:3168 [wandb_run.py:_wait_for_finish():1489] got exit ret: done: true
exit_result {
}
file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 4017
  total_bytes: 4017
}

2021-01-29 23:06:59,439 INFO    MainThread:3168 [wandb_run.py:_show_files():1711] logging synced files
2021-01-29 23:06:59,442 INFO    MainThread:3168 [internal.py:handle_exit():139] Internal process exited
